# Generated by Django 2.2.17 on 2020-12-30 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlinked',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tripreview',
            name='auther',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tripreview',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trip.Trip'),
        ),
        migrations.AddField(
            model_name='tripplaces',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trip.Place'),
        ),
        migrations.AddField(
            model_name='tripplaces',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='places', to='trip.Trip'),
        ),
        migrations.AddField(
            model_name='tripimage',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='trip.Trip'),
        ),
        migrations.AddField(
            model_name='trip',
            name='activities',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trip.TripActivities'),
        ),
        migrations.AddField(
            model_name='trip',
            name='auther',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trip',
            name='category',
            field=models.ManyToManyField(blank=True, to='trip.TripCategory'),
        ),
        migrations.AddField(
            model_name='companions',
            name='companion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companions',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trip.Trip'),
        ),
    ]
